### ISSUE TITLE
サイト制作の必須条件

### ISSUE THREAD

**Issue by SanMurakami** [Ixy194194/ixy194194.github.io#3]
# 必須条件
- GitHub Pagesのみで動作すること
- 外部APIを叩かない
- JSフレームワークを使う場合はGatsbyやNext.jsなどの静的サイトジェネレーターを使うこと
  GoogleはJSをレンダリングしてくれるのでSEO的には心配ないが、Twitterなどは貼り付けた際にOGPが正常に機能しないため

**Comment by Ixy194194** [comment]
ありがとうございます！

**Comment by EbiseLutica** [comment]
個人的にはAstroをおすすめしています
静的サイトジェネレーターの一つですが、ブラウザで動かすときにJavaScriptを必要としない（つけることも可能）というスグレモノです
https://astro.build/

**Comment by CookieRamen** [comment]
@EbiseLutica Astroは登場してまもなく今後開発が継続されるか不透明な上、ドキュメントもまだまだ少ないので既に構築されているNext.jsで行きたいと思います。
