### ISSUE TITLE
一部の文字が重なっている

### ISSUE THREAD

**Issue by ugokitakunai** [Ixy194194/ixy194194.github.io#51]
![Screenshot_2023-04-18-08-11-26-45_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/90504762/232629701-83fc8ec2-4992-4d1c-b7e7-d1be00d11c84.jpg)

画像の通り
Contact: (Email)のように一行にするといいかもしれない

**Comment by ugokitakunai** [comment]
環境
Firefox for Android
Reno5 A, Android 12

**Comment by ugokitakunai** [comment]
そもそも下の欄がスマホだと2行になってるって時点でデザイン的にあまりよろしくない気がするので
別のページか何かにまとめたほうがいいかもしれない

**Comment by irhdevel** [comment]
> Twitter, Instagram, ... のところにもEmailを追加して、ホバー（タップ）するとポップアップが表示されるいいかもしれませんね...

モーダル化したPRを投げてみました #53
