### ISSUE TITLE
画像の圧縮

### ISSUE THREAD

**Issue by WhiteHawk-taka** [Ixy194194/ixy194194.github.io#52]
現在掲載されている画像を [TinyJPG](https://tinyjpg.com/) などのツールを通すと80%近くの圧縮ができました。  
画質との兼ね合いにもなりますが、圧縮することで読み込み時間の短縮・ SEO の向上を図ることができると思います。
また、 JPG 形式にこだわりが無ければ、 [WebP 形式](https://developer.mozilla.org/ja/docs/Web/Media/Formats/Image_types#webp_%E7%94%BB%E5%83%8F)での対応も検討すると良いかもしれません。

**Comment by irhdevel** [comment]
WebPとかを検討するのであれば、比較しつつ変換できる https://squoosh.app もおすすめかもしれません。
